### ISSUE TITLE
App crash when selecting countries

### ISSUE THREAD

**Issue by jacobabrennan** [Lambda-School-Labs/labs9-map-scratcher#102]
![bug2](https://user-images.githubusercontent.com/2273265/51870717-63b24b00-2322-11e9-8c87-94dca2a4b6f1.png)

React often crashes on my computer when I select countries, especially when my CPU is under stress, leading me to believe it may be a race condition.

**Comment by kyranmccann** [comment]
updated render logic to wait for everything before proceeding
