### ISSUE TITLE
Econuntered two children with the same key

### ISSUE THREAD

**Issue by samsisle** [Lambda-School-Labs/labs9-map-scratcher#105]
I'm not sure what the affect of what is stated in the warning is, but it has been occurring consistently (but I don't know exactly when). No idea what is triggering it. Whoever was in charge of creating the FriendDropdown component should possibly check this out. I'm not sure how it's connected to the CurrentUser component either.

![screenshot 177](https://user-images.githubusercontent.com/28912696/51877365-c86ca600-2320-11e9-832e-7eb3ab082366.png)

Curious note: the console.log for the user's Id is slow by three console.logs (versus the default userId), but I don't see a flash depicting the wrong data being shown

**Comment by kyranmccann** [comment]
someone added the default user as a friend of itself. fixed.
